// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqytggobxaixzmdiplpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxeXRnZ29ieGFpeHptZGlwbHBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NDk2MjUsImV4cCI6MjA2NzAyNTYyNX0.ydNNLq0HO4WP-7oOqEzwZoTRK_KwMKxyBLuEIqvUfg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});